# This is a zola config. https://www.getzola.org/

# The URL the site will be built for
base_url = "https://www.zerotrickpony.com/unducking"

title = "Unducked Typescript Aliases"
description = "A comparison of techniques for Typescript aliases of primative types"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

[extra]
# Put all your custom variables here
